import {Campaign} from "@/components/campaigns/table/columns";

type Campaign = {
  id: number;
  title: string;
  lastEditBy: string;
  isActive: boolean;
  startDate: string; // Date type not allowed for Tanstack table accessor
  endDate: string;
  description: string;
  targetAmount: number;
  donationOptions: { amount: number; description: string }[];
  images: { url: string; name: string }[];
};

const data: Campaign[] = [
  {
    id: 1,
    title: "Summer Charity Drive",
    lastEditBy: "Sarah",
    isActive: true,
    startDate: "2024-06-01",
    endDate: "2024-08-31",
    description: "Support our summer charity drive and make a difference!",
    targetAmount: 8000,
    donationOptions: [
      { amount: 10, description: "Bronze Supporter - Help us with a small contribution!" },
      { amount: 25, description: "Silver Supporter - Your support can change lives!" },
      { amount: 50, description: "Gold Supporter - Join us in making a big impact!" },
    ],
    images: [
    ],
  },
  {
    id: 2,
    title: "Education for All",
    lastEditBy: "Michael",
    isActive: true,
    startDate: "2024-09-15",
    endDate: "2024-12-15",
    description: "Empower children through quality education.",
    targetAmount: 10000,
    donationOptions: [
      { amount: 15, description: "Book Sponsor - Help children by sponsoring books!" },
      { amount: 30, description: "School Supplies Sponsor - Support with school essentials!" },
      { amount: 100, description: "Education Champion - Make a significant impact!" },
    ],
    images: [
    ],
  },
];

/*
const data: Campaign[] = [
  {
    id: 1,
    title: "Blood and Bone",
    lastEditBy: "Candice",
    isActive: false,
    startDate: "22-Aug-2023",
    endDate: "06-Feb-2024",
  },
  {
    id: 2,
    title: "Good Night, and Good Luck.",
    lastEditBy: "Kelcie",
    isActive: true,
    startDate: "28-Nov-2023",
    endDate: "19-Mar-2024",
  },
  {
    id: 3,
    title: "From the Earth to the Moon",
    lastEditBy: "Natty",
    isActive: false,
    startDate: "27-Nov-2023",
    endDate: "06-Feb-2024",
  },
  {
    id: 4,
    title: "Live Free or Die Hard",
    lastEditBy: "Gonzalo",
    isActive: true,
    startDate: "18-Aug-2023",
    endDate: "26-Mar-2024",
  },
  {
    id: 5,
    title: "Tales of Terror (Kaidan Shin Mimibukuro)",
    lastEditBy: "Flo",
    isActive: true,
    startDate: "14-Oct-2023",
    endDate: "30-Mar-2024",
  },
  {
    id: 6,
    title: "Ruling Class, The",
    lastEditBy: "Cathi",
    isActive: false,
    startDate: "02-Oct-2023",
    endDate: "14-Feb-2024",
  },
  {
    id: 7,
    title: "Hungry Hill",
    lastEditBy: "Lyndsay",
    isActive: true,
    startDate: "09-Aug-2023",
    endDate: "29-Feb-2024",
  },
  {
    id: 8,
    title: "Can Mr. Smith Get to Washington Anymore?",
    lastEditBy: "Sanderson",
    isActive: false,
    startDate: "22-Dec-2023",
    endDate: "20-Mar-2024",
  },
  {
    id: 9,
    title: "Hold Back the Dawn",
    lastEditBy: "Morgun",
    isActive: true,
    startDate: "22-Oct-2023",
    endDate: "03-Apr-2024",
  },
  {
    id: 10,
    title: "Journey to Saturn (Rejsen til Saturn)",
    lastEditBy: "Brandice",
    isActive: false,
    startDate: "24-Dec-2023",
    endDate: "07-Apr-2024",
  },
  {
    id: 11,
    title: "Signal, The",
    lastEditBy: "Hagen",
    isActive: false,
    startDate: "07-Sep-2023",
    endDate: "12-Apr-2024",
  },
  {
    id: 12,
    title: "Forgetting the Girl",
    lastEditBy: "Greggory",
    isActive: false,
    startDate: "13-Aug-2023",
    endDate: "26-Apr-2024",
  },
  {
    id: 13,
    title: "Counterfeit Traitor, The",
    lastEditBy: "Carmine",
    isActive: true,
    startDate: "09-Oct-2023",
    endDate: "09-Feb-2024",
  },
  {
    id: 14,
    title: "Papa's Delicate Condition",
    lastEditBy: "Leesa",
    isActive: false,
    startDate: "13-Nov-2023",
    endDate: "14-Mar-2024",
  },
  {
    id: 15,
    title: "Return of Don Camillo, The (Retour de Don Camillo, Le)",
    lastEditBy: "Nicol",
    isActive: false,
    startDate: "26-Aug-2023",
    endDate: "10-Feb-2024",
  },
  {
    id: 16,
    title: "Wolf",
    lastEditBy: "Koenraad",
    isActive: false,
    startDate: "27-Sep-2023",
    endDate: "09-Apr-2024",
  },
  {
    id: 17,
    title: "Face (Visage)",
    lastEditBy: "Lizzy",
    isActive: false,
    startDate: "14-Aug-2023",
    endDate: "14-Feb-2024",
  },
  {
    id: 18,
    title: "Motorcycle Diaries, The (Diarios de motocicleta)",
    lastEditBy: "Teodorico",
    isActive: true,
    startDate: "17-Oct-2023",
    endDate: "28-Mar-2024",
  },
  {
    id: 19,
    title: "Lulu on the Bridge",
    lastEditBy: "Kincaid",
    isActive: false,
    startDate: "02-Aug-2023",
    endDate: "23-Apr-2024",
  },
  {
    id: 20,
    title: "Seopyeonje",
    lastEditBy: "Mickie",
    isActive: true,
    startDate: "18-Dec-2023",
    endDate: "11-Apr-2024",
  },
  {
    id: 21,
    title: "Breakin' 2: Electric Boogaloo",
    lastEditBy: "Teodora",
    isActive: true,
    startDate: "20-Sep-2023",
    endDate: "03-Feb-2024",
  },
  {
    id: 22,
    title: "Paying the Price: Killing the Children of Iraq",
    lastEditBy: "Leyla",
    isActive: true,
    startDate: "27-Dec-2023",
    endDate: "14-Feb-2024",
  },
  {
    id: 23,
    title: "Tess of the Storm Country",
    lastEditBy: "Nobie",
    isActive: false,
    startDate: "19-Sep-2023",
    endDate: "03-Feb-2024",
  },
  {
    id: 24,
    title: "Skeletons",
    lastEditBy: "Raphaela",
    isActive: true,
    startDate: "01-Nov-2023",
    endDate: "21-Mar-2024",
  },
  {
    id: 25,
    title: "North Star (a.k.a. Tashunga)",
    lastEditBy: "Fredi",
    isActive: true,
    startDate: "22-Sep-2023",
    endDate: "08-Apr-2024",
  },
  {
    id: 26,
    title: "47 Samurai (Chûshingura) (Loyal 47 Ronin, The)",
    lastEditBy: "Florida",
    isActive: true,
    startDate: "06-Sep-2023",
    endDate: "03-Feb-2024",
  },
  {
    id: 27,
    title: "Whatever Happened to Aunt Alice?",
    lastEditBy: "Clerc",
    isActive: false,
    startDate: "09-Nov-2023",
    endDate: "21-Mar-2024",
  },
  {
    id: 28,
    title: "Afterburn",
    lastEditBy: "Gardy",
    isActive: false,
    startDate: "17-Sep-2023",
    endDate: "23-Feb-2024",
  },
  {
    id: 29,
    title: "Decline of Western Civilization, The",
    lastEditBy: "Justinian",
    isActive: true,
    startDate: "09-Dec-2023",
    endDate: "01-Feb-2024",
  },
  {
    id: 30,
    title: "Starcrash (a.k.a. Star Crash)",
    lastEditBy: "Roze",
    isActive: true,
    startDate: "19-Nov-2023",
    endDate: "09-Mar-2024",
  },
  {
    id: 31,
    title: "Thirst (a.k.a. Three Strange Loves) (Törst)",
    lastEditBy: "Terrence",
    isActive: true,
    startDate: "14-Dec-2023",
    endDate: "28-Apr-2024",
  },
  {
    id: 32,
    title: "Honey, We Shrunk Ourselves",
    lastEditBy: "Avictor",
    isActive: false,
    startDate: "26-Dec-2023",
    endDate: "15-Apr-2024",
  },
  {
    id: 33,
    title: "Defiant Ones, The",
    lastEditBy: "Aeriela",
    isActive: true,
    startDate: "03-Sep-2023",
    endDate: "16-Mar-2024",
  },
  {
    id: 34,
    title: "The UFO Incident",
    lastEditBy: "Forster",
    isActive: false,
    startDate: "09-Aug-2023",
    endDate: "14-Mar-2024",
  },
  {
    id: 35,
    title: "20 Years After",
    lastEditBy: "Merrill",
    isActive: false,
    startDate: "03-Aug-2023",
    endDate: "06-Apr-2024",
  },
  {
    id: 36,
    title: "Woman in Black, The",
    lastEditBy: "Patience",
    isActive: true,
    startDate: "18-Nov-2023",
    endDate: "08-Mar-2024",
  },
  {
    id: 37,
    title: "Hearts Divided",
    lastEditBy: "Anica",
    isActive: true,
    startDate: "26-Sep-2023",
    endDate: "18-Feb-2024",
  },
  {
    id: 38,
    title: "The Learning Tree",
    lastEditBy: "Bekki",
    isActive: true,
    startDate: "03-Aug-2023",
    endDate: "18-Mar-2024",
  },
  {
    id: 39,
    title: "All Is Lost",
    lastEditBy: "Melody",
    isActive: false,
    startDate: "01-Aug-2023",
    endDate: "14-Mar-2024",
  },
  {
    id: 40,
    title: "Tied",
    lastEditBy: "Florencia",
    isActive: true,
    startDate: "19-Sep-2023",
    endDate: "08-Apr-2024",
  },
  {
    id: 41,
    title: "Death Proof",
    lastEditBy: "Kym",
    isActive: false,
    startDate: "07-Sep-2023",
    endDate: "19-Mar-2024",
  },
  {
    id: 42,
    title: "Fly II, The",
    lastEditBy: "Carolin",
    isActive: true,
    startDate: "29-Dec-2023",
    endDate: "17-Apr-2024",
  },
  {
    id: 43,
    title: "Shrek Forever After (a.k.a. Shrek: The Final Chapter)",
    lastEditBy: "Anne-marie",
    isActive: true,
    startDate: "21-Aug-2023",
    endDate: "09-Mar-2024",
  },
  {
    id: 44,
    title: "Thinner",
    lastEditBy: "Christa",
    isActive: false,
    startDate: "05-Dec-2023",
    endDate: "23-Mar-2024",
  },
  {
    id: 45,
    title: "Hellraiser: Deader",
    lastEditBy: "Brigg",
    isActive: false,
    startDate: "19-Nov-2023",
    endDate: "22-Mar-2024",
  },
  {
    id: 46,
    title: "Hobbit: An Unexpected Journey, The",
    lastEditBy: "Tawsha",
    isActive: true,
    startDate: "08-Dec-2023",
    endDate: "16-Feb-2024",
  },
  {
    id: 47,
    title: "976-EVIL II",
    lastEditBy: "Theda",
    isActive: false,
    startDate: "19-Sep-2023",
    endDate: "28-Apr-2024",
  },
  {
    id: 48,
    title: "Aeon Flux",
    lastEditBy: "Lesya",
    isActive: true,
    startDate: "10-Dec-2023",
    endDate: "01-Feb-2024",
  },
  {
    id: 49,
    title: "Grumpier Old Men",
    lastEditBy: "Winnah",
    isActive: true,
    startDate: "07-Nov-2023",
    endDate: "03-Apr-2024",
  },
  {
    id: 50,
    title: "Ladies Man, The",
    lastEditBy: "Gareth",
    isActive: true,
    startDate: "03-Dec-2023",
    endDate: "24-Feb-2024",
  },
];
*/

export default data;
