export const DonationType =  {
  ANONYMOUS: 'ANONYMOUS',
  INDIVIDUAL_WITH_TAX_DEDUCTION: 'INDIVIDUAL_WITH_TAX_DEDUCTION',
  GROUP_WITH_TAX_DEDUCTION: 'GROUP_WITH_TAX_DEDUCTION',
  WITHOUT_TAX_DEDUCTION: 'WITHOUT_TAX_DEDUCTION',
  ALL: "ALL"
};

export const SelectDonationType = {
  INDIVIDUAL: "Individual", 
  GROUP: "Group", 
  ANONYMOUS: "Anonymous", 
  ALL: "All"
}